columns: 
  - case_id : category
  - continent: category 
  - education_of_employee : category 
  - has_job_experience : category 
  - requires_job_training : category
  - no_of_employees : int 
  - yr_of_estab : int 
  - region_of_employment : category 
  - prevailing_wage : int 
  - unit_of_wage : category
  - full_time_psition : category
  - case_status : category 


numerical_columns: 
  - no_of_employees : int 
  - yr_of_estab : int 
  - prevailing_wage : int 


categorical_columns: 
  - case_id : category
  - continent: category 
  - education_of_employee : category 
  - has_job_experience : category 
  - requires_job_training : category
  - region_of_employment : category 
  - unit_of_wage : category
  - full_time_psition : category
  - case_status : category 



drop_columns : 
 - case_id : category
 - yr_of_estab : int 



# for data_transformations 

num_features: 
  - no_of_employees
  - prevailing_wage

or_columns: 
  - has_job_experience 
  - requires_job_training 
  - full_time_psition
  - education_of_employee


oh_columns: 
  - continent
  - unit_of_wage 
  - region_of_employment


transform_columns: 
  - no_of_employees 
  


  